# Generated by Django 5.2.3 on 2025-06-22 23:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(help_text='e.g., Cereal, Legume, Vegetable, etc.', max_length=50)),
                ('growing_season', models.CharField(help_text='e.g., Rainy season, Dry season, All year', max_length=100)),
                ('maturity_days', models.PositiveIntegerField(help_text='Days to maturity')),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='crop_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Crop',
                'verbose_name_plural': 'Crops',
                'db_table': 'farms_crop',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CropVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('maturity_days', models.PositiveIntegerField(help_text='Days to maturity for this variety')),
                ('yield_per_hectare', models.DecimalField(decimal_places=2, help_text='Expected yield per hectare', max_digits=8)),
                ('resistance_traits', models.TextField(blank=True, help_text='Disease/pest resistance traits')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='farms.crop')),
            ],
            options={
                'verbose_name': 'Crop Variety',
                'verbose_name_plural': 'Crop Varieties',
                'db_table': 'farms_cropvariety',
                'ordering': ['crop__name', 'name'],
                'unique_together': {('crop', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('total_area', models.DecimalField(decimal_places=2, help_text='Total farm area in hectares', max_digits=10)),
                ('location', models.CharField(help_text='Farm location/address', max_length=300)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('soil_type', models.CharField(blank=True, max_length=100)),
                ('climate_zone', models.CharField(blank=True, max_length=100)),
                ('water_source', models.CharField(blank=True, max_length=200)),
                ('farm_image', models.ImageField(blank=True, null=True, upload_to='farm_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='accounts.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_farms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farm',
                'verbose_name_plural': 'Farms',
                'db_table': 'farms_farm',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=200)),
                ('farmer_email', models.EmailField(blank=True, max_length=254)),
                ('farmer_phone', models.CharField(blank=True, max_length=17)),
                ('location', models.CharField(max_length=300)),
                ('allocated_hectares', models.DecimalField(decimal_places=2, max_digits=8)),
                ('season_year', models.PositiveIntegerField()),
                ('expected_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('actual_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crops_grown', models.ManyToManyField(blank=True, to='farms.crop')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_records', to='farms.farm')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Farmer Record',
                'verbose_name_plural': 'Farmer Records',
                'db_table': 'farms_farmerrecord',
                'ordering': ['-season_year', 'farmer_name'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('size', models.DecimalField(decimal_places=2, help_text='Block size in hectares', max_digits=8)),
                ('plant_population', models.PositiveIntegerField(blank=True, help_text='Number of plants per hectare', null=True)),
                ('expected_yield', models.DecimalField(blank=True, decimal_places=2, help_text='Expected yield in tons', max_digits=8, null=True)),
                ('soil_ph', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)])),
                ('irrigation_type', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('planting_date', models.DateField(blank=True, null=True)),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('actual_harvest_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block_manager', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['farm_manager', 'block_manager', 'staff']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_blocks', to=settings.AUTH_USER_MODEL)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farms.crop')),
                ('variety', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farms.cropvariety')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='farms.farm')),
            ],
            options={
                'verbose_name': 'Block/Field',
                'verbose_name_plural': 'Blocks/Fields',
                'db_table': 'farms_block',
                'ordering': ['farm__name', 'name'],
                'unique_together': {('farm', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FarmStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Farm Manager'), ('supervisor', 'Supervisor'), ('field_worker', 'Field Worker'), ('technician', 'Technician'), ('security', 'Security')], max_length=20)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hire_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='farms.farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farm Staff',
                'verbose_name_plural': 'Farm Staff',
                'db_table': 'farms_farmstaff',
                'ordering': ['farm__name', 'user__first_name'],
                'unique_together': {('farm', 'user')},
            },
        ),
    ]
