# Generated by Django 5.2.3 on 2025-06-24 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='block',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='block',
            name='actual_yield',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual yield achieved', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='block_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_blocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FieldInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_type', models.CharField(choices=[('seeds', 'Seeds'), ('fertilizer', 'Fertilizer'), ('pesticide', 'Pesticide'), ('tools', 'Tools'), ('equipment', 'Equipment'), ('supplies', 'General Supplies')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(help_text='e.g., kg, liters, pieces', max_length=50)),
                ('min_stock_level', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location', models.CharField(blank=True, help_text='Storage location', max_length=200)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='farms.block')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='farms.farm')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Field Inventory',
                'verbose_name_plural': 'Field Inventory',
                'db_table': 'farms_fieldinventory',
                'ordering': ['item_name'],
            },
        ),
        migrations.CreateModel(
            name='FieldTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('task_type', models.CharField(choices=[('planting', 'Planting'), ('watering', 'Watering'), ('fertilizing', 'Fertilizing'), ('weeding', 'Weeding'), ('pest_control', 'Pest Control'), ('harvesting', 'Harvesting'), ('soil_prep', 'Soil Preparation'), ('inspection', 'Field Inspection'), ('maintenance', 'Equipment Maintenance'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('due_date', models.DateTimeField()),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='farms.block')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='farms.farm')),
            ],
            options={
                'verbose_name': 'Field Task',
                'verbose_name_plural': 'Field Tasks',
                'db_table': 'farms_fieldtask',
                'ordering': ['-due_date', '-priority'],
            },
        ),
    ]
