# Generated by Django 5.2.3 on 2025-06-24 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_alter_block_unique_together_block_actual_yield_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerrecord',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_records', to='farms.block'),
        ),
    ]
