# Generated by Django 5.2.3 on 2025-06-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_farmerrecord_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerrecord',
            name='farming_experience',
            field=models.PositiveIntegerField(blank=True, help_text='Years of farming experience', null=True),
        ),
        migrations.AddField(
            model_name='farmerrecord',
            name='irrigation_method',
            field=models.CharField(blank=True, help_text='Type of irrigation used', max_length=100),
        ),
        migrations.AddField(
            model_name='farmerrecord',
            name='registration_date',
            field=models.DateField(blank=True, help_text='Date farmer joined the program', null=True),
        ),
        migrations.AddField(
            model_name='farmerrecord',
            name='soil_type',
            field=models.CharField(blank=True, help_text="Soil type on farmer's land", max_length=100),
        ),
        migrations.AlterField(
            model_name='farmerrecord',
            name='location',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
