# Generated by Django 5.2.3 on 2025-06-25 16:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('farms', '0004_farmerrecord_farming_experience_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('financial', 'Financial Reports'), ('production', 'Production Reports'), ('operational', 'Operational Reports'), ('marketplace', 'Marketplace Reports'), ('executive', 'Executive Reports')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Report Categories',
                'ordering': ['category_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('budget_vs_actual', 'Budget vs Actual Analysis'), ('profit_loss', 'Profit & Loss Statement'), ('cost_analysis', 'Cost Analysis Report'), ('cash_flow', 'Cash Flow Report'), ('financial_summary', 'Financial Summary'), ('yield_analysis', 'Yield Analysis Report'), ('crop_performance', 'Crop Performance Report'), ('seasonal_comparison', 'Seasonal Comparison Report'), ('block_efficiency', 'Block Efficiency Report'), ('farmer_performance', 'Farmer Performance Report'), ('activity_completion', 'Activity Completion Report'), ('task_management', 'Task Management Report'), ('equipment_utilization', 'Equipment Utilization Report'), ('inventory_report', 'Inventory Status Report'), ('staff_productivity', 'Staff Productivity Report'), ('sales_performance', 'Sales Performance Report'), ('market_analysis', 'Market Price Analysis'), ('transaction_report', 'Transaction Report'), ('customer_analysis', 'Customer Analysis Report'), ('executive_dashboard', 'Executive Dashboard'), ('kpi_scorecard', 'KPI Scorecard'), ('organization_overview', 'Organization Overview')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='farms.farm')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.organization')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reports.reportcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], max_length=10)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_exports', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='reports.report')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('budget_vs_actual', 'Budget vs Actual Analysis'), ('profit_loss', 'Profit & Loss Statement'), ('cost_analysis', 'Cost Analysis Report'), ('cash_flow', 'Cash Flow Report'), ('financial_summary', 'Financial Summary'), ('yield_analysis', 'Yield Analysis Report'), ('crop_performance', 'Crop Performance Report'), ('seasonal_comparison', 'Seasonal Comparison Report'), ('block_efficiency', 'Block Efficiency Report'), ('farmer_performance', 'Farmer Performance Report'), ('activity_completion', 'Activity Completion Report'), ('task_management', 'Task Management Report'), ('equipment_utilization', 'Equipment Utilization Report'), ('inventory_report', 'Inventory Status Report'), ('staff_productivity', 'Staff Productivity Report'), ('sales_performance', 'Sales Performance Report'), ('market_analysis', 'Market Price Analysis'), ('transaction_report', 'Transaction Report'), ('customer_analysis', 'Customer Analysis Report'), ('executive_dashboard', 'Executive Dashboard'), ('kpi_scorecard', 'KPI Scorecard'), ('organization_overview', 'Organization Overview')], max_length=50)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_schedules', to='farms.farm')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_schedules', to='accounts.organization')),
                ('recipients', models.ManyToManyField(related_name='report_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_run'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('budget_vs_actual', 'Budget vs Actual Analysis'), ('profit_loss', 'Profit & Loss Statement'), ('cost_analysis', 'Cost Analysis Report'), ('cash_flow', 'Cash Flow Report'), ('financial_summary', 'Financial Summary'), ('yield_analysis', 'Yield Analysis Report'), ('crop_performance', 'Crop Performance Report'), ('seasonal_comparison', 'Seasonal Comparison Report'), ('block_efficiency', 'Block Efficiency Report'), ('farmer_performance', 'Farmer Performance Report'), ('activity_completion', 'Activity Completion Report'), ('task_management', 'Task Management Report'), ('equipment_utilization', 'Equipment Utilization Report'), ('inventory_report', 'Inventory Status Report'), ('staff_productivity', 'Staff Productivity Report'), ('sales_performance', 'Sales Performance Report'), ('market_analysis', 'Market Price Analysis'), ('transaction_report', 'Transaction Report'), ('customer_analysis', 'Customer Analysis Report'), ('executive_dashboard', 'Executive Dashboard'), ('kpi_scorecard', 'KPI Scorecard'), ('organization_overview', 'Organization Overview')], max_length=50)),
                ('template_content', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='accounts.organization')),
            ],
            options={
                'ordering': ['report_type', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type'], name='reports_rep_report__dbb097_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_by'], name='reports_rep_created_61f2ca_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['organization'], name='reports_rep_organiz_108bde_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['farm'], name='reports_rep_farm_id_81c617_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='reports_rep_status_c732ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reportexport',
            unique_together={('report', 'export_format')},
        ),
        migrations.AlterUniqueTogether(
            name='reporttemplate',
            unique_together={('report_type', 'organization', 'is_default')},
        ),
    ]
