# Generated by Django 5.2.3 on 2025-06-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_create_default_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportexport',
            name='content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reportexport',
            name='file_content',
            field=models.TextField(blank=True),
        ),
    ]
