# Generated by Django 5.2.3 on 2025-06-22 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget', '0001_initial'),
        ('calendar', '0001_initial'),
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='calendar.cropcalendar'),
        ),
        migrations.AddField(
            model_name='budget',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_budgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budget',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='farms.farm'),
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='budget.budgetcategory'),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='budget.budget'),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.budgetcategory'),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgettemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgettemplate',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_templates', to='farms.crop'),
        ),
        migrations.AddField(
            model_name='budgettemplateitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.budgetcategory'),
        ),
        migrations.AddField(
            model_name='budgettemplateitem',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_items', to='budget.budgettemplate'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_items', to='budget.budget'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.budgetcategory'),
        ),
        migrations.AddField(
            model_name='incomeitem',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_items', to='budget.budget'),
        ),
    ]
