# Generated by Django 5.2.3 on 2025-08-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='company_brand',
            field=models.CharField(blank=True, help_text='Company or brand name', max_length=200),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='main_category',
            field=models.CharField(choices=[('land_development', 'Farm Land Development'), ('input_cost', 'Input Cost'), ('transport', 'Transport of Input'), ('mechanization', 'Farm Mechanization'), ('labour', 'Labour Cost'), ('insurance', 'Insurance'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='product_name',
            field=models.CharField(blank=True, help_text='Specific product name/variety', max_length=200),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='rate_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate per bag/kg/ltr', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='sub_category',
            field=models.CharField(choices=[('virgin_land', 'Virgin Land Development'), ('land_clearing', 'Land Clearing'), ('seeds', 'Seeds'), ('fertilizers', 'Fertilizers'), ('herbicides', 'Herbicides'), ('pesticides', 'Pesticides'), ('ploughing', 'Ploughing'), ('harrowing', 'Harrowing'), ('planting', 'Planting'), ('weeding', 'Weeding'), ('fertilizer_application', 'Fertilizer Application'), ('harvesting', 'Harvesting'), ('bagging', 'Bagging and Packaging'), ('haulage', 'Haulage'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
