# Generated by Django 5.2.3 on 2025-08-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_budgetitem_company_brand_budgetitem_main_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='company',
            field=models.CharField(blank=True, help_text='Company name', max_length=200),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='particulars',
            field=models.CharField(blank=True, help_text='Category/type (Particulars column)', max_length=200),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='product_brand_name',
            field=models.CharField(blank=True, help_text='Product Brand Name', max_length=200),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantity', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='sequence_number',
            field=models.PositiveIntegerField(default=1, help_text='S.No. from Excel table'),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='total_cost_per_ha',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total Cost/ha', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='units',
            field=models.CharField(blank=True, help_text='Units (kg, bags, liters, ha)', max_length=50),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='rate_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate per (Bag/Kg/Ltr)', max_digits=8, null=True),
        ),
    ]
