# Generated by Django 5.2.3 on 2025-08-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_budgetitem_company_budgetitem_particulars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='actual_yield',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual yield achieved', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='buyer_name',
            field=models.CharField(blank=True, help_text='Name of buyer/customer', max_length=200),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='expected_yield',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected yield in tons/kg', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='market_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current market price per unit', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('partial', 'Partial Payment'), ('paid', 'Fully Paid'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='sale_date',
            field=models.DateField(blank=True, help_text='Date of sale', null=True),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='company',
            field=models.CharField(blank=True, help_text='Company name or Buyer name', max_length=200),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='product_brand_name',
            field=models.CharField(blank=True, help_text='Product Brand Name or Crop Variety', max_length=200),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantity or Expected Yield', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='rate_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate per unit or Price per unit', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='total_cost_per_ha',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total Cost/ha or Revenue per ha', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='units',
            field=models.CharField(blank=True, help_text='Units (kg, bags, liters, ha, tons)', max_length=50),
        ),
    ]
